name: Build and Release NMEA2000 Analyzer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Visual Studio for .NET Framework or .NET Core/6.0+ projects
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      # Restore NuGet packages
      - name: Restore dependencies
        run: dotnet restore

      # Build the solution
      - name: Build Solution
        run: |
          msbuild NMEA2000Analyzer.sln /p:Configuration=Release

      # Package the output into a ZIP file
      - name: Create Release ZIP
        run: |
          mkdir artifacts
          # Compress the build output into a ZIP file
          powershell Compress-Archive -Path "bin\Release\*" -DestinationPath "artifacts\Release.zip"

      # Upload the ZIP file as an artifact for debugging or manual download
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: NMEA2000Analyzer
          path: artifacts/Release.zip

  release:
    name: Create GitHub Release
    runs-on: windows-latest
    needs: build
    permissions:
      contents: write

    steps:
      - name: Upload Release Artifact to GitHub
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ github.run_number }}
          artifacts: "artifacts/Release.zip"
